source 'https://rubygems.org'

gem 'rails'
gem 'bootstrap-sass'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-ui-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'sdoc', group: :doc
gem 'bcrypt'
gem 'ckeditor'
gem "paperclip"
gem 'will_paginate'
#gem 'bootstrap-will_paginate', '~> 0.0.10' this is for infinite scrolling. not needed otherwise.
gem 'betterlorem'
gem 'faker'
gem 'record_tag_helper'

  
group :development, :test do
  gem 'byebug'
  gem 'sqlite3'
end

group :test do
  gem 'rails-controller-testing'
  gem 'minitest-reporters'
end

group :development do
  gem 'web-console'
end

group :production do
  gem 'pg'
  gem 'puma'
  gem 'rails_12factor'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
