# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d42bea58006b920dc5334c3ee4677d3dc693ed60563f00f9f6e0b0cccd2b3e68050d07246b07639d098a87f4b00ce7e1a451a187f0c713c59e932d38fd620370

test:
  secret_key_base: 314abe12b548c9f3eca3d9400eccd50618ea06f2f28b4df035bf312143431671a3e9621ec25cbf67988f837d0ca766f794f79d1d1975df32067107bdb1b9eb54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
